### ISSUE TITLE
Can I get log (information, error, debug,..) when I published my app on Google store?

### ISSUE THREAD

**Issue by vnext-tungns** [DeployGate/deploygate-android-sdk-sample#4]
When I deploy my app on the deploygate, then it will send log to the deploygate, then I can see the log.
But I Want to ask you, Can I get log (information, error, debug,..) when I published my app on Google store?
Tks

**Comment by tnj** [comment]
No, you can't. DeployGate SDK only works with DeployGate client app and builds installed through it.

Please post further questions to [forums](https://deploygate.com/forums) next time, because here is a issue tracker dedicated for sample DeployGate SDK sample, which our support team isn't watching. Thanks!
